### ISSUE TITLE
issue angular2

### ISSUE THREAD

**Issue by sante85** [hjalmers/angular2-generic-table#15]
After import module, at runtime i have
Uncaught SyntaxError: Unexpected token export
at line
export {GtExpandedRow} from './src/generic-table/components/gt-expanding-row/gt-expanding-row.component';

I have git master version.
Can you release a stable version correctely?
thanks

**Comment by sante85** [comment]
index.ts:1             Uncaught SyntaxError: Unexpected token export

export {GtExpandedRow} from './src/generic-table/components/gt-expanding-row/gt-expanding-row.component';
export {GenericTableComponent} from './src/generic-table/generic-table.component';
export {GtConfig} from './src/generic-table/interfaces/gt-config';
export {GtInformation} from './src/generic-table/interfaces/gt-information';
export {GtPagingInfo} from './src/generic-table/interfaces/gt-paging-info';
export {GtTexts} from './src/generic-table/interfaces/gt-texts';
export * from './src/generic-table/generic-table.module';



//////////////////
// WEBPACK FOOTER
// ./~/angular2-generic-table/index.ts
// module id = 165
// module chunks = 0

**Comment by hjalmers** [comment]
I'm not sure I follow your issue, are you using angular-cli, angular-seed etc? You could always clone the project and see how it's supposed to be set up otherwise. Please note that the published versions are marked as release candidates so if you're not sure how you'd like to use this table component maybe you should wait until a more stable release is published. However it should work if you run latest angular-cli version and just run "npm install angular2-generic-table --save" and follow the examples provided (some of them needs to be updated though).

**Comment by sante85** [comment]
i use webpack





[conf file.zip](https://github.com/hjalmers/angular2-generic-table/files/567202/conf.file.zip)

**Comment by hjalmers** [comment]
could you please provide a plunker or be more specific, it's packaged as a commonjs module targeting es5 so it shouldn't be any different than adding any another library, especially if you've added it as an npm dependency...

**Comment by sante85** [comment]
I have install plugin from npm. I use webpack and bower.

**Comment by sante85** [comment]
If I import your source in my project, go correctely. At this point difference is in compilation mode.
Did you have an idea to resolve problem?

thanks

**Comment by hjalmers** [comment]
Have you included any other libraries in your project?

**Comment by sante85** [comment]
yes and i not have any problem.
