### ISSUE TITLE
Pagination not working in Firefox

### ISSUE THREAD

**Issue by torsten-transfollow** [hjalmers/angular2-generic-table#28]
Firefox(s): 49.0.2, 50.0.0, 50.0.1
angular2-generic-table: 1.0.0-rc.7

When I use Firefox en click next / previous seems to open my default page (Angular2 routing configuration). The pagination works in Safari and Chrome. 

I see a event.preventDefault() in the nextPage and previousPage functions. If I comment these lines out it works in firefox (as well as safari and chrome).
It seems that firefox determines that there is no event and fails to then execute the function.
It seems that event is undefined in Firefox.

In your demo you can see this because the page is refreshed (not preventing the href #)

**Comment by hjalmers** [comment]
If you remove the event.preventDefault() I belive that the page will jump to the start of the page i.e. if your table or page is long and you've scrolled down the page will jump up to the beginning. But another workaround for the moment, as we're planning on adding a paging component (see issue #2), would be to just remove the href part from links all together, the only downside will be that they won't look like links anymore since bootstrap 4 only adds link style to a tags with href attributes. But you could add your own styling to solve that of course:)

We'll take this into consideration as we add the paging component though, and I'll fix this for the examples too:)

**Comment by hjalmers** [comment]
This should have been resolved now:)

**Comment by torsten-transfollow** [comment]
Thanks!
